In [5]:
from selenium import webdriver
from bs4 import BeautifulSoup
import zipfile
import pandas as pd
from io import StringIO
import requests
import csv
import time
import random

# Using Selenium to download Zip file from website

In [2]:
def ChromeDriver(url):
    #the path for your chromedriver should be adjusted to your path
    driver = webdriver.Chrome(executable_path='C:\chromedriver.exe')
    driver.get(url)
    #time.sleep allows the brower to wait 5 seconds before returning
    time.sleep(5)
    return driver

link = "https://ga-covid19.ondemand.sas.com/docs/ga_covid_data.zip"
ChromeDriver(link)

# Unzip zip file and save demographics_sum.csv as a dataframe

In [3]:
#must be changed to users path for downloads
zf = zipfile.ZipFile(r"C:\Users\wjg39\Downloads\ga_covid_data.zip")

Georgia_data = pd.read_csv(zf.open('demographics_sum.csv'))

# Georgia race and ethnicity dataframe. Data is aggregated in the Google Sheet

In [4]:
Georgia_data

              Ethnicity                              race  cases  Deaths
0       Hispanic/Latino            African-American/Black    903      13
1       Hispanic/Latino     American Indian/Alaska Native     47       0
2       Hispanic/Latino                             Asian     90       0
3       Hispanic/Latino  Native Hawaiian/Pacific Islander     94       0
4       Hispanic/Latino                             Other  14796     158
5       Hispanic/Latino                           Unknown   5877       6
6       Hispanic/Latino                             White  19702     256
7   Non-Hispanic/Latino            African-American/Black  72019    2893
8   Non-Hispanic/Latino     American Indian/Alaska Native    124       7
9   Non-Hispanic/Latino                             Asian   3999     130
10  Non-Hispanic/Latino  Native Hawaiian/Pacific Islander    218       7
11  Non-Hispanic/Latino                             Other   3708      17
12  Non-Hispanic/Latino                           Unknown   2935      32
13  Non-Hispanic/Latino                             White  85991    3539
14              Unknown            African-American/Black  12653      19
15              Unknown     American Indian/Alaska Native     51       0
16              Unknown                             Asian   1215       0
17              Unknown  Native Hawaiian/Pacific Islander     84       0
18              Unknown                             Other   5234       5
19              Unknown                           Unknown  77005      61
20              Unknown                             White  16180      19